import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/footer/footerComponent";
import Navbar from "@/components/common/navbar/navbarComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
      <body className={inter.className}>
       
        {children}
        <Footer/>
        
        </body>
    </html>
  );
}
